apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: data-hub-configs
  namespace: data-hub
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: data-hub-team-deployment
    namespace: flux-system
  path: ./kustomizations/apps/data-hub-configs
  prune: true
  postBuild:
    substitute:
      data_hub_core_dags_stable_image_repo: docker.io/elifesciences/data-hub-core-dags # {"$imagepolicy": "data-hub:data-hub-core-dags-stable:name"}
      data_hub_core_dags_stable_image_tag: 0.0.26 # {"$imagepolicy": "data-hub:data-hub-core-dags-stable:tag"}
      data_hub_data_science_dags_stable_image_repo: docker.io/elifesciences/data-science-dags # {"$imagepolicy": "data-hub:data-hub-data-science-dags-stable:name"}
      data_hub_data_science_dags_stable_image_tag: 0.0.22 # {"$imagepolicy": "data-hub:data-hub-data-science-dags-stable:tag"}
      data_hub_peerscout_dags_stable_image_repo: docker.io/elifesciences/peerscout-dags # {"$imagepolicy": "data-hub:data-hub-peerscout-dags-stable:name"}
      data_hub_peerscout_dags_stable_image_tag: 0.0.2 # {"$imagepolicy": "data-hub:data-hub-peerscout-dags-stable:tag"}
      data_hub_ejp_xml_pipeline_stable_image_repo: docker.io/elifesciences/data-hub-ejp-xml-pipeline # {"$imagepolicy": "data-hub:data-hub-ejp-xml-pipeline-stable:name"}
      data_hub_ejp_xml_pipeline_stable_image_tag: 0.0.5 # {"$imagepolicy": "data-hub:data-hub-ejp-xml-pipeline-stable:tag"}
      data_hub_metrics_api_stable_image: ghcr.io/elifesciences/data-hub-metrics-api:0.0.11 # {"$imagepolicy": "data-hub:data-hub-metrics-api-stable"}
      data_hub_core_dags_unstable_image_repo: docker.io/elifesciences/data-hub-core-dags_unstable # {"$imagepolicy": "data-hub:data-hub-core-dags-unstable:name"}
      data_hub_core_dags_unstable_image_tag: HEAD-2fd56141-20250620.1533 # {"$imagepolicy": "data-hub:data-hub-core-dags-unstable:tag"}
      data_hub_data_science_dags_unstable_image_repo: docker.io/elifesciences/data-science-dags_unstable # {"$imagepolicy": "data-hub:data-hub-data-science-dags-unstable:name"}
      data_hub_data_science_dags_unstable_image_tag: develop-6a7c3acb-20250623.1125 # {"$imagepolicy": "data-hub:data-hub-data-science-dags-unstable:tag"}
      data_hub_peerscout_dags_unstable_image_repo: docker.io/elifesciences/peerscout-dags_unstable # {"$imagepolicy": "data-hub:data-hub-peerscout-dags-unstable:name"}
      data_hub_peerscout_dags_unstable_image_tag: HEAD-97338d07-20241029.0909 # {"$imagepolicy": "data-hub:data-hub-peerscout-dags-unstable:tag"}
      data_hub_ejp_xml_pipeline_unstable_image_repo: docker.io/elifesciences/data-hub-ejp-xml-pipeline_unstable # {"$imagepolicy": "data-hub:data-hub-ejp-xml-pipeline-unstable:name"}
      data_hub_ejp_xml_pipeline_unstable_image_tag: HEAD-07813fb5-20250618.1957 # {"$imagepolicy": "data-hub:data-hub-ejp-xml-pipeline-unstable:tag"}
      data_hub_metrics_api_unstable_image: ghcr.io/elifesciences/data-hub-metrics-api_unstable:main-d7f3fbde-20250623.1627 # {"$imagepolicy": "data-hub:data-hub-metrics-api-unstable"}
