apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ai-mcp-api--stg
  labels:
    app: data-ai-mcp-api--stg
  namespace: data-ai-bot
spec:
  selector:
    matchLabels:
      app: data-ai-mcp-api--stg
  template:
    metadata:
      labels:
        app: data-ai-mcp-api--stg
    spec:
      containers:
      - name: data-ai-mcp-api
        image: ghcr.io/de-code/py-conf-mcp_unstable:main-0031a6d8-20250806.0957 # {"$imagepolicy": "data-ai-bot:py-conf-mcp-unstable"}
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_FILE
          value: "/config/mcp-server--stg.yaml"
        - name: OPENSEARCH_USERNAME_FILE_PATH
          value: /.secrets/opensearch/username
        - name: OPENSEARCH_PASSWORD_FILE_PATH
          value: /.secrets/opensearch/password
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /.secrets/gcp/service_account
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: data-ai-bot-configs-volume
          mountPath: /config/
          readOnly: true
        - name: opensearch-secret-volume
          mountPath: /.secrets/opensearch/
          readOnly: true
        - name: gcp-secret-volume
          mountPath: /.secrets/gcp/
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1500m
            memory: 500Mi
      volumes:
      - name: data-ai-bot-configs-volume
        configMap:
          name: data-ai-bot-configs
      - name: opensearch-secret-volume
        secret:
          secretName: opensearch-staging-admin-password
      - name: gcp-secret-volume
        secret:
          secretName: gcp
---
apiVersion: v1
kind: Service
metadata:
  name: data-ai-mcp-api--stg
  namespace: data-ai-bot
spec:
  selector:
    app: data-ai-mcp-api--stg
  ports:
  - port: 8080
