apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ai-bot--prod
  labels:
    app: data-ai-bot--prod
  namespace: data-ai-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ai-bot--prod
  template:
    metadata:
      labels:
        app: data-ai-bot--prod
    spec:
      containers:
      - name: data-ai-bot
        image: ghcr.io/de-code/data-ai-bot:0.0.7 # {"$imagepolicy": "data-ai-bot:data-ai-bot-stable"}
        imagePullPolicy: IfNotPresent
        env:
        - name: OPENAI_BASE_URL
          value: "https://api.openai.com/v1"
        - name: OPENAI_MODEL_ID
          value: "gpt-4o-mini"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api
              key: openai_api_key
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: signing_secret
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: app_token
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: bot_user_oauth_token
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1500m
            memory: 500Mi
