apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: data-ai-bot-configs
  namespace: data-ai-bot
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: data-hub-team-deployment
    namespace: flux-system
  path: ./kustomizations/apps/data-ai-bot-configs
  prune: true
