---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sciencebeam-parser-basic-auth--prod
  namespace: sciencebeam
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: sciencebeam-parser-basic-auth--prod
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        usersFile: "{{ .auth }}"
  dataFrom:
  - extract:
      key: data-team/sciencebeam/parser-basic-auth
