apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: data-hub-peerscout-dags-stable
  namespace: data-hub
spec:
  interval: 5m
  image: docker.io/elifesciences/peerscout-dags
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: data-hub-peerscout-dags-stable
  namespace: data-hub
spec:
  imageRepositoryRef:
    name: data-hub-peerscout-dags-stable
    namespace: data-hub
  policy:
    semver:
      range: '*'
