apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: phoenix
  namespace: data-ai-bot
spec:
  interval: 5m
  image: docker.io/arizephoenix/phoenix
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: phoenix
  namespace: data-ai-bot
spec:
  imageRepositoryRef:
    name: phoenix
    namespace: data-ai-bot
  filterTags:
    pattern: '^version-(?P<version>.*)'
    extract: '$version'
  policy:
    semver:
      range: '*'
