apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: py-conf-mcp-unstable
  namespace: data-ai-bot
spec:
  interval: 5m
  image: ghcr.io/de-code/py-conf-mcp_unstable
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: py-conf-mcp-unstable
  namespace: data-ai-bot
spec:
  imageRepositoryRef:
    name: py-conf-mcp-unstable
    namespace: data-ai-bot
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
