---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: data-hub-metrics-api-redis--stg
  namespace: data-hub
spec:
  interval: 5m
  chart:
    spec:
      chart: valkey
      version: "3.0.2"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    global:
      defaultStorageClass: data-hub-gp3
    architecture: standalone
    auth:
      enabled: false
    primary:
      resourcesPreset: none
