apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-ai-bot

configMapGenerator:
- name: data-ai-bot-configs
  files:
  - data-ai-bot--prod.yaml
  - data-ai-bot--stg.yaml
  - mcp-server--stg.yaml
generatorOptions:
  disableNameSuffixHash: true
