toolDefinitions:
  fromPythonFunction:
    - name: get_joke
      module: py_conf_mcp.tools.example.joke
      key: get_joke
      description: |-
        Fetches a random programming joke.

  fromPythonClass:
    - name: how_to_use_this_tool
      description: |-
        Explain to the user how to use this AI tool.
        This also summarised what this tool knows.
        Also provides some example prompts.
      module: py_conf_mcp.tools.sources.static
      className: StaticContentTool
      initParameters:
        content: |-
          You can ask for jokes..

          Example prompts:
            - Tell me a joke.

    - name: get_programming_joke_via_web_api
      description: |-
        Fetches a random joke.
      module: py_conf_mcp.tools.sources.web_api
      className: WebApiTool
      initParameters:
        url: 'https://v2.jokeapi.dev/joke/Programming?type=single&safe-mode&blacklistFlags=nsfw'

    - name: get_joke_via_web_api
      description: |-
        Fetches a random joke.
      module: py_conf_mcp.tools.sources.web_api
      className: WebApiTool
      initParameters:
        url: 'https://v2.jokeapi.dev/joke/{{ category }}?type={{ type }}&safe-mode&blacklistFlags=nsfw'
      inputs:
        category:
          type: str
          default: 'Programming'
          # Note: 'Spooky' and 'Christmas' are not available in the API as single joke types
          enum:
            - Any
            - Programming
            - Misc
            - Dark
            - Pun
            - Spooky
            - Christmas
        type:
          type: str
          default: 'single'
          title: Joke Type
          enum:
            - single
            - twopart

    - name: search_ecr
      description: |-
        Searches for Early Career Researchers (ECR).
        Use if asked to list or find ECRs.
      module: py_conf_mcp.tools.sources.web_api
      className: WebApiTool
      initParameters:
        url: 'https://opensearch-prod.data-hub:9200/ecr_v1/_search'
        verify_ssl: false
        basic_auth:
          username: '{{ read_secret_from_env("OPENSEARCH_USERNAME_FILE_PATH") }}'
          password: '{{ read_secret_from_env("OPENSEARCH_PASSWORD_FILE_PATH") }}'
        json_template: |-
          {
            "query": {
              "bool": {
                "must": [
                  {
                    "multi_match": {
                      "query": {{ query | tojson }},
                      "fields": [
                        "name^3",
                        "subject_areas^2",
                        "keywords"
                      ],
                      "type": "most_fields",
                      "fuzziness": "AUTO",
                      "operator": "or",
                      "minimum_should_match": 1
                    }
                  }
                ]
              }
            },
            "size": 10
          }
        response_template: |-
          {%- if response_json.hits.total.value > 0 -%}
            {%- if response_json.hits.total.value == 1 -%}
          1 ECR found:
            {%- else -%}
          {{ response_json.hits.total.value }} ECRs found:
            {%- endif -%}
          {%- else -%}
            No ECRs found.
          {%- endif %}
          {%- if response_json.hits.total.value > 0 %}
          {%- for hit in response_json.hits.hits %}
          - {{ hit._source.name }}
            Email: {{ hit._source.email }}
            Institution: {{ hit._source.institution }}
            Website URL: {{ hit._source.website_url }}
            Subject areas: {{ hit._source.subject_areas }}
            Keywords: {{ hit._source.keywords }}
          {%- endfor %}
          {%- endif %}
      inputs:
        query:
          type: str
          title: Search Query
          description: 'The search query to find ECRs.'

server:
  name: 'Test MCP server'
  tools:
    - get_joke_via_web_api
    - search_ecr
