apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: data-hub-metrics-api-stable
  namespace: data-hub
spec:
  imageRepositoryRef:
    name: data-hub-metrics-api-stable
    namespace: data-hub
  policy:
    semver:
      range: '*'
