apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: data-hub-metrics-api-unstable
  namespace: data-hub
spec:
  interval: 5m
  image: ghcr.io/elifesciences/data-hub-metrics-api_unstable
