bigQueryToOpenSearch:
  - dataPipelineId: bigquery_to_opensearch_data_pipeline_ecr
    target:
      openSearch:
        hostname: 'opensearch-prod'
        port: 9200
        timeout: 120
        verifyCertificates: False
        secrets:
          parametersFromFile:
            - parameterName: username
              filePathEnvName: OPENSEARCH_USERNAME_FILE_PATH
            - parameterName: password
              filePathEnvName: OPENSEARCH_PASSWORD_FILE_PATH
        indexName: 'ecr_v1'
        updateIndexSettings: False
        updateMappings: True
        operationMode: 'update'
        upsert: True
        indexSettings:
          # Note: These settings can usually only be applied to a new index.
          mappings:
            properties:
                person_id:
                  type: "keyword"
    source:
      bigQuery:
        projectName: 'elife-data-pipeline'
        sqlQuery: |-
          SELECT
            Person_ID AS person_id,
            Name AS name,
            Email AS email,
            Institution AS institution,
            Webpage_URL AS website_url,
            ARRAY(SELECT Subject_Area_Name FROM UNNEST(Subject_Areas)) AS subject_areas,
            ARRAY(SELECT Keyword FROM UNNEST(Keywords)) AS keywords,
            Updated_Timestamp AS updated_timestamp
          FROM `elife-data-pipeline.prod.mv_Editorial_Early_Career_Reviewer`
    fieldNamesFor:
      id: person_id
      timestamp: updated_timestamp
    state:
      initialState:
        startTimestamp: '2012-01-01+00:00'
      stateFile:
        bucketName: '{ENV}-elife-data-pipeline'
        objectName: 'airflow-config/bigquery-to-opensearch/{ENV}-state-ecr.json'
    batchSize: 100
