importFilesFrom:
  - kubernetes-pipeline-data-science-pipelines--prod.config.yaml
  - kubernetes-pipeline-ejp-xml-pipelines--prod.config.yaml
  - kubernetes-pipeline-other-core-pipelines--prod.config.yaml
  - kubernetes-pipeline-web-api-pipelines--prod.config.yaml
  - kubernetes-pipeline-data-hub-metrics-api-pipelines--prod.config.yaml
