gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: "imported_timestamp"
spreadsheets:
    # this is the public editor profile
  - dataPipelineId: 'public_editor_profile'
    spreadsheetId: "1VnpuiY3o4iCEIEWjCKfXFFyowxTfTxzno2VU5UnRINE"
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-spreadsheet/{ENV}-public_editor_profile-state.txt'
    sheets:
      - sheetName: 'BREs'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'public_editor_profile'
        tableWriteAppend: True
        fixedSheetRecordMetadata:
          - metadataSchemaFieldName: 'editor_role'
            fixedSheetValue: "bre"

      - sheetName: 'Senior Editors'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'public_editor_profile'
        tableWriteAppend: True
        fixedSheetRecordMetadata:
          - metadataSchemaFieldName: 'editor_role'
            fixedSheetValue: "senior editor"

      - sheetName: 'Editor on Leave Periods'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'editor_on_leave_period'
        tableWriteAppend: False

  - dataPipelineId: 'bre_distribution'
    spreadsheetId: '1nQcLBO_yIumkXousRg_-l9Kx1HmiG7NcvDg1vkrdK-0'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-spreadsheet/{ENV}-bre_distribution-state.txt'
    sheets:
      - sheetName: 'BRE distribution_current'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'BRE_Distribution'
        tableWriteAppend: True
        #inSheetRecordMetadata:
        #  - metadataSchemaFieldName: 'metadata_example'
        #    metadataLineIndex: 1

  # unmatched manuscripts and override hypothesis matching
  - dataPipelineId: 'unmatched_and_override_hypothesis_matching'
    spreadsheetId: '15QcK8w-ssB7109RQEDtFpJPZ0J5HTGxoHa_2TtpMBbg'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-spreadsheet/{ENV}-unmatched_and_override_hypothesis_matching-state.txt'
    sheets:
      - sheetName: 'unmatched_list'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'unmatched_manuscripts'
        tableWriteAppend: true

      - sheetName: 'override_hypothesis_matching'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'override_hypothesis_matching'
        tableWriteAppend: true

  # deleted hypothesis annotations
  - dataPipelineId: 'deleted_hypothesis_annotations'
    spreadsheetId: '1naXfcCxvTC8fLPhR8K1znC9B5DMxGP7HMpp-2CcO_sY'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-spreadsheet/{ENV}-deleted_hypothesis_annotations-state.txt'
    sheets:
      - sheetName: 'deleted_hypothesis_list'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'deleted_hypothesis_annotations'
        tableWriteAppend: true

  # reviewed preprint publication date
  - dataPipelineId: 'reviewed_preprint_publication_date'
    spreadsheetId: '1amAlKvdLcaDp5W8Z8g77NmkwbMF5n_u89ArSqPMO8jg'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-spreadsheet/{ENV}-reviewed_preprint_publication_date-state.txt'
    sheets:
      - sheetName: 'publication_date'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'reviewed_preprint_publication_date'
        tableWriteAppend: true

  # meca path update
  - dataPipelineId: 'reviewed_preprint_meca_path_update'
    spreadsheetId: '1mctCQuNFBjSn97Lihy7_vBO6z7-N-oqyLv4clyi6zHg'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-spreadsheet/{ENV}-reviewed_preprint_meca_path_update-state.txt'
    sheets:
      - sheetName: 'meca_path'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'reviewed_preprint_meca_path_update'
        tableWriteAppend: true

    # eJP invalid manuscripts to exclude
  - dataPipelineId: 'invalid_manuscripts_to_exclude'
    spreadsheetId: '1xGUTxD4U67kcjNuJ7zXz1XSkK-0wCiR6h-Om64dp2pM'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-spreadsheet/{ENV}-invalid_manuscripts_to_exclude-state.txt'
    sheets:
      - sheetName: 'invalid_manuscripts'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'invalid_manuscripts_to_exclude'
        tableWriteAppend: true
