apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp
  namespace: data-ai-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: gcp
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: data-team/data-ai-bot/gcp
