apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-api
  namespace: data-ai-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: openai-api
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: data-team/data-ai-bot/openai-api
